### ISSUE TITLE
Structure Learning

### ISSUE THREAD

**Issue by zsunberg** [sisl/BayesNets.jl#30]
Hi all,

In preparing for AA228 Project 1, I have started to realize that BayesNets.jl 1.0 is not very well-suited to structure learning using the Bayesian Score as a metric. This is for two reasons.

1. There appears to be no API Mechanism for adding or removing edges
2. The bayesian score calculation has nothing to do with the CPDs in the BayesNet. The only thing that matters is the data. I found this very confusing when I took the class.

Do we want to add some tools to facilitate structure learning? Or should we just recommend that students write their own? How much turnaround time is there to get changes pushed to the official version on METADATA?

The simplest thing we could do is simply add a more convenient bayesian_score method:
```julia
bayesian_score(g::LightGraphs.DiGraph, node_to_name::Vector{Symbol}, data::DataFrame)
```

Or we could add a type for structure learning
```julia
type BayesNetStructure
    g::DiGraph
    names::Vector{Symbol}
    _name_to_node::Nullable{Dict{Symbol, Int}} # this is of course redundant, not sure if it would be useful to have for performance
end
```

What do you think? Should we just let students create their own tools? maybe just put the bayesian_score method as an example in the course materials

**Comment by zsunberg** [comment]
Actually I guess the best way to store a graph structure for calculating the bayesian score is as parent lists, not an edge list (as I think LightGraphs stores it). Am I right in saying this?

**Comment by zsunberg** [comment]
Actually I guess a DiGraph has adjacency lists

**Comment by mykelk** [comment]
Instead of DiGraph, use the DAG type defined in BayesNets.jl. We can add functions to help with structure learning. (For 228, I would recommend that you implement something like K2 yourself to make sure that things are not too hard or too easy for the students.)

**Comment by mykelk** [comment]
It would be great for @tawheeler to review your additions since he has worked on this new API.

**Comment by tawheeler** [comment]
_There is no API for adding or removing edges_
Correct - we want to ensure that there are always valid CPDs. Instead there are mechanisms for adding CPDs, `push!(BN, cpd)`, and we should probably add `deleteat!(BN, nodename)`.

_The bayesian score calculation has nothing to do with the CPDs in the BayesNet_
Right. With discrete Bayes nets all you need is the structure, and the CPDs can be directly computed.

_The simplest thing we could do is simply add a more convenient bayesian_score method:_
We could add `bayesian_score(dag::DAG, data::DataFrame, prior::DirichletPrior)`, which would assume that dag nodes are ordered in the same order as columns in the data, or use `node_to_name::Vector{Symbol}` as an optional input.

_Or we could add a type for structure learning_
If I understand correctly, this would be for incremental structure learning algorithms rather than all-at-once `fit` calls.

- `fit(::BayesNet{CPDType}, data, params)` is all you need for all-at-once
- If you need to keep track of a DAG during training your fit function can just do that internally

We went away from such structures for general Bayes nets because you don't have valid CPDs computed, and thus don't have a valid BN object. For discrete Bayesian networks things are a little different, because the CPD table has a prescribed way of being computed. The DiscreteBayesNet fit function just maintains a list of parent lists and can call `bayesian_score_component` as it searches.

_Instead of DiGraph, use the DAG type defined in BayesNets.jl_
`DAG` is typealiased to `DiGraph`, and one would capture all of the structure information you need. `DAG` is exported so we can use that. 

_Should we just let students create their own tools?_
I got a lot out of implementing and verifying the implementation of the log Bayes score myself. Having to read, understand, implement, and test is a very valuable skill.  Doesn't `fit(::DiscreteBayesNet, data, params::GreedyHillClimbing)` implement the assignment?

**Comment by tawheeler** [comment]
FWIW I added a `delete!(bn::BayesNet, target::NodeName)` function. It issues a warning when the removed cpd has children.

**Comment by tawheeler** [comment]
So this is not really a BayesNets issue - more of an aa228 issue. Okay to close and do this via email?

**Comment by zsunberg** [comment]
I am going to submit a PR to add one more method to bayesian_score today

**Comment by tawheeler** [comment]
Sure, no problem
