### ISSUE TITLE
Ordering of distributions in CategoricalCPD

### ISSUE THREAD

**Issue by zsunberg** [sisl/BayesNets.jl#37]
Hey @tawheeler, this was a question from piazza:

> If the parents of A are X,  Y and Z, then is the ordering for the distributions in CategoricalCPD:
> 
> X,Y,Z
> 0,0,0
> 1,0,0
> 0,1,0
> 1,1,0
> 0,0,1
> 1,0,1
>⋮

I wasn't 100% sure what the ordering is. Do you think you could update the documentation with notation similar to theirs? Thanks!

**Comment by tawheeler** [comment]
From categorical_cpd.jl

"""
A categorical distribution, P(x|parents(x)) where all parents are discrete integers 1:Nᵢ

The ordering of `distributions` array follows the convention in Decision Making Under Uncertainty.
Suppose a variable has three discrete parents. The first parental instantiation
assigns all parents to their first bin. The second will assign the first
parent (as defined in `parents`) to its second bin and the other parents
to their first bin. The sequence continues until all parents are instantiated
to their last bins.
"""

This is equivalent to:

X,Y,Z
1,1,1
2,1,1
1,2,1
2,2,1
1,1,2
...

Note that CategoricalCPD uses 1:N rather than 0:N-1

**Comment by tawheeler** [comment]
pushed 7bb0c94

**Comment by zsunberg** [comment]
Yeah I saw the docstring - it was just a little difficult to be sure I was
reading it right. Thanks for updating
