### ISSUE TITLE
TeX-free rendering

### ISSUE THREAD

**Issue by tawheeler** [sisl/BayesNets.jl#53]
`writememe` currently uses TikzGraphs to render to LaTeX.  It would be nice to have a rendering method without so many dependencies. Maybe something that works with Cairo.jl.

**Comment by rejuvyesh** [comment]
Since we seem to be using LightGraphs as our backend, we could consider using `graphplot` from `PlotRecipes.jl`.

So as long as the `bn.dag` is not empty, we can use `graphplot(bn.dag, names=names(bn))`. Although it doesn't look as nice. We could consider writing our own recipe based on that though?

**Comment by mykelk** [comment]
@rejuvyesh possibly. One of my summer students was going to create a lightweight D3.js package for graphlayout that we can use here.

**Comment by tawheeler** [comment]
Luxor + NetworkLayout would work.

**Comment by itsdfish** [comment]
Hi. I am interested in using BayesNet. However, I am experiencing a lot of difficulty installing TikzGraphs.jl due to its dependencies. I was wondering if any progress has been made towards a new rendering setup? Also, in the meantime, do you have advice on installing pgf? Currently I receive the following message:

```
(base) dfish@dfish-MS-7850:~$ sudo apt-get install pgf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package pgf is a virtual package provided by:
  texlive-pictures 2015.20160320-1ubuntu0.1 [Not candidate version]

E: Package 'pgf' has no installation candidate
```

I could not figure out how to install pgf via texlive and I cannot install miktex on my computer. Thank you.

**Comment by mykelk** [comment]
You'll want to follow the instructions here: https://github.com/JuliaTeX/TikzPictures.jl

I'm still hoping someone will create a tex-free renderer.

**Comment by mykelk** [comment]
For tex-free rendering, I might recommend https://github.com/JuliaGraphs/GraphPlot.jl.

This would involve adding a call to GraphPlot.jl here:
https://github.com/sisl/BayesNets.jl/blob/master/src/io.jl

**Comment by itsdfish** [comment]
Thank you. I appreciate the advice. I will try these alternative setups.

**Comment by mykelk** [comment]
@mossr has made this dream come true
